### ISSUE TITLE
rollup shortcode cannot find file in sub directory

### ISSUE THREAD

**Issue by stanislavprokopov** [Snapstromegon/eleventy-plugin-rollup#13] opened 2023-10-28 06:08 UTC
I am trying to make rollup work with my setup, the source code is located under `./src` folder, when i try to use rollup shortcode it fails to find the js file, if i move the `/src/static/js/main.js` to root `/static/js/main.js` then it is able to find it and build under `/public/static/js/main-abc.js` but when I open localhost it fails to load it giving 404. Not sure whats wrong with my setup, it does not matter if i use `importScriptsAbsoluteFrom: 'src', useAbsoluteScriptPaths: true,` or not, it still cant find the source in `./src/` folder.

What am I missing here :?

```
const rollupPlugin = require('eleventy-plugin-rollup');

module.exports = function (eleventyConfig) {
  eleventyConfig.setBrowserSyncConfig({
    files: './public/static/**/*.(css|js)',
  });

  eleventyConfig.addWatchTarget('static/js/*');

  eleventyConfig.addPlugin(rollupPlugin, {
    rollupOptions: {
      output: {
        format: 'es',
        dir: 'public/static/js',
      },
    },
  });

  return {
    dir: {
      input: 'src',
      output: 'public',
    },
  };
};
```

Example repo: https://github.com/odevtools/fakester

Error: 
```
[11ty] 1. Having trouble writing to "public/index.html" from "./src/index.md" (via EleventyTemplateError)
[11ty] 2. (./src/_includes/base.njk)
[11ty]   EleventyShortcodeError: Error with Nunjucks shortcode `rollup` (via Template render error)
[11ty] 3. ENOENT: no such file or directory, open 'static/js/main.js' (via Template render error)
[11ty]
[11ty] Original error stack trace: Error: ENOENT: no such file or directory, open 'static/js/main.js'
```

**Comment by Snapstromegon** [comment] 2023-10-29 01:34
Hi @stanislavprokopov,
this weekend I'm out on an event, but I will take a look at it during the next week and see how I can help you. In the meantime you could already check my personal blog repo, which is also using this package: https://github.com/Snapstromegon/hoeser.dev/blob/b5c650edda5e065b92c34c72a2ed6bbb0806ba99/.eleventy.js#L75

**Comment by Snapstromegon** [comment] 2023-10-30 17:56
Hey @stanislavprokopov, the repo you linked as an example is not available to me (most likely because it's private). If you could make it public (and maybe respond here, so I get a notification) I can take a look at it.

**Comment by stanislavprokopov** [comment] 2023-10-30 18:50
@Snapstromegon yeah sorry, forgot it was private, now its public, I would appreciate if you could have a look at it.

**Comment by Snapstromegon** [comment] 2023-10-31 00:24
Okay @stanislavprokopov, I took a look at the repo and I think the root cause is a misunderstanding of how `importScriptsAbsoluteFrom` works. It does not mean where you have to put your source scripts, but where your rollup output has to be imported from in the generated script paths. This is sometimes required in more complicated setups.

In your specific case you can just ignore the `importScriptsAbsoluteFrom` config.

To fix your issue, you need to change your import paths instead, so they are relative to the root of the project (e.g. *src/static/js/main.js* instead of *static/js/main.js*).

By the way, the paths passed to `eleventyConfig.addWatchTarget()` are also relative to the project root (/ directory of your 11ty config), so the `eleventyConfig.addWatchTarget('static/js/*');` in your example does nothing.

**Comment by stanislavprokopov** [comment] 2023-10-31 09:43
@Snapstromegon thanks for your help, changing path to relative to the root worked, I guess the Eleventy inputDir config variable got me confused to believe that all plugins will be using it to search for stuff.

**Comment by Snapstromegon** [comment] 2023-10-31 20:20
Ah, I see where you're coming from.
I often see it, that the stuff that 11ty handles only via plugins like images, css and js, is placed in a folder "assets" next to src, so you actually wouldn't want the plugin to use the 11ty input path by default. This is sometimes done, so 11ty doesn't try to pick up files not meant for it as templates (e.g. a README.md for some included js tool or similar).

Since the issue is resolved, I'm closing this thread.

**Closed as completed by Snapstromegon** 2023-10-31 20:20 UTC
